package view_administrador;

import model.Investidor;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author Darcio Rodrigues
 */
public class Menu_Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Administrador
     */
    public Menu_Administrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1 = new javax.swing.JLabel();
        bt_cadastrarInvestidor = new javax.swing.JButton();
        lbl2 = new javax.swing.JLabel();
        bt_excluirInvestidor = new javax.swing.JButton();
        lbl3 = new javax.swing.JLabel();
        bt_cadastrarMoeda = new javax.swing.JButton();
        lbl4 = new javax.swing.JLabel();
        bt_excluirMoeda = new javax.swing.JButton();
        lbl5 = new javax.swing.JLabel();
        bt_saldoInvestidor = new javax.swing.JButton();
        lbl6 = new javax.swing.JLabel();
        bt_extratoInvestidor = new javax.swing.JButton();
        lbl7 = new javax.swing.JLabel();
        bt_atualizarCotacao = new javax.swing.JButton();
        lbl8 = new javax.swing.JLabel();
        bt_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl1.setText("1.");

        bt_cadastrarInvestidor.setText("Cadastrar  novo investidor");
        bt_cadastrarInvestidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastrarInvestidorActionPerformed(evt);
            }
        });

        lbl2.setText("2.");

        bt_excluirInvestidor.setText("Excluir investidor");
        bt_excluirInvestidor.setActionCommand("");
        bt_excluirInvestidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluirInvestidorActionPerformed(evt);
            }
        });

        lbl3.setText("3.");

        bt_cadastrarMoeda.setText("Cadastrar nova criptomoeda");
        bt_cadastrarMoeda.setActionCommand("");

        lbl4.setText("4.");

        bt_excluirMoeda.setText("Excluir criptomoeda");
        bt_excluirMoeda.setActionCommand("");

        lbl5.setText("5.");

        bt_saldoInvestidor.setText("Consultar saldo de um investidor");
        bt_saldoInvestidor.setActionCommand("");

        lbl6.setText("6.");

        bt_extratoInvestidor.setText("Consultar extrato de um investidor");
        bt_extratoInvestidor.setActionCommand("");

        lbl7.setText("7.");

        bt_atualizarCotacao.setText("Atualizar cotação das criptomoedas");
        bt_atualizarCotacao.setActionCommand("");

        lbl8.setText("8.");

        bt_sair.setText("Sair");
        bt_sair.setActionCommand("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_atualizarCotacao))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_extratoInvestidor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_cadastrarInvestidor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_cadastrarMoeda))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_excluirInvestidor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_saldoInvestidor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_excluirMoeda))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_sair)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1)
                    .addComponent(bt_cadastrarInvestidor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2)
                    .addComponent(bt_excluirInvestidor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl3)
                    .addComponent(bt_cadastrarMoeda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl4)
                    .addComponent(bt_excluirMoeda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl5)
                    .addComponent(bt_saldoInvestidor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl6)
                    .addComponent(bt_extratoInvestidor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl7)
                    .addComponent(bt_atualizarCotacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl8)
                    .addComponent(bt_sair))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_cadastrarInvestidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastrarInvestidorActionPerformed
        Cadastrar_Investidor ci = new Cadastrar_Investidor();
        this.setVisible(false);
        ci.setVisible(true);
    }//GEN-LAST:event_bt_cadastrarInvestidorActionPerformed

    private void bt_excluirInvestidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluirInvestidorActionPerformed

        Excluir_Investidor ei = new Excluir_Investidor();
        this.setVisible(false);
        ei.setVisible(true);
    }//GEN-LAST:event_bt_excluirInvestidorActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Menu_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Menu_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Menu_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Menu_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Menu_Administrador().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_atualizarCotacao;
    private javax.swing.JButton bt_cadastrarInvestidor;
    private javax.swing.JButton bt_cadastrarMoeda;
    private javax.swing.JButton bt_excluirInvestidor;
    private javax.swing.JButton bt_excluirMoeda;
    private javax.swing.JButton bt_extratoInvestidor;
    private javax.swing.JButton bt_sair;
    private javax.swing.JButton bt_saldoInvestidor;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    // End of variables declaration//GEN-END:variables
}
