/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view_investidor;

import controller_investidor.ControllerCotacao_Investidor;

/**
 *
 * @author Darcio Rodrigues
 */
public class Menu_Investidor extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Investidor
     */
    public Menu_Investidor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_saldo = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        bt_extrato = new javax.swing.JButton();
        lbl2 = new javax.swing.JLabel();
        bt_despositar = new javax.swing.JButton();
        lbl3 = new javax.swing.JLabel();
        bt_sacar = new javax.swing.JButton();
        lbl4 = new javax.swing.JLabel();
        bt_comprar = new javax.swing.JButton();
        lbl5 = new javax.swing.JLabel();
        bt_vender = new javax.swing.JButton();
        lbl6 = new javax.swing.JLabel();
        bt_atualizar = new javax.swing.JButton();
        lbl7 = new javax.swing.JLabel();
        Sair = new javax.swing.JLabel();
        bt_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_saldo.setText("Consultar saldo");
        bt_saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_saldoActionPerformed(evt);
            }
        });

        lbl1.setText("1.");

        bt_extrato.setText("Consultar extrato");
        bt_extrato.setActionCommand("");
        bt_extrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_extratoActionPerformed(evt);
            }
        });

        lbl2.setText("2.");

        bt_despositar.setText("Depositar");
        bt_despositar.setActionCommand("");
        bt_despositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_despositarActionPerformed(evt);
            }
        });

        lbl3.setText("3.");

        bt_sacar.setText("Sacar");
        bt_sacar.setActionCommand("");
        bt_sacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sacarActionPerformed(evt);
            }
        });

        lbl4.setText("4.");

        bt_comprar.setText("Comprar criptomoedas");
        bt_comprar.setActionCommand("");
        bt_comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_comprarActionPerformed(evt);
            }
        });

        lbl5.setText("5.");

        bt_vender.setText("Vender criptomoedas");
        bt_vender.setActionCommand("");
        bt_vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_venderActionPerformed(evt);
            }
        });

        lbl6.setText("6.");

        bt_atualizar.setText("Atualizar cotação");
        bt_atualizar.setActionCommand("");
        bt_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_atualizarActionPerformed(evt);
            }
        });

        lbl7.setText("7.");

        Sair.setText("8.");

        bt_sair.setText("Sair");
        bt_sair.setActionCommand("");
        bt_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_despositar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_extrato))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_saldo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_sacar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_comprar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_vender))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_atualizar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Sair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_sair)))
                .addContainerGap(281, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bt_atualizar, bt_comprar, bt_despositar, bt_extrato, bt_sacar, bt_sair, bt_saldo, bt_vender});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_saldo)
                    .addComponent(lbl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_extrato)
                    .addComponent(lbl2))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_despositar)
                    .addComponent(lbl3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_sacar)
                    .addComponent(lbl4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_comprar)
                    .addComponent(lbl5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl6)
                    .addComponent(bt_vender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl7)
                    .addComponent(bt_atualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sair)
                    .addComponent(bt_sair))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bt_atualizar, bt_comprar, bt_despositar, bt_extrato, bt_sacar, bt_sair, bt_saldo, bt_vender});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_saldoActionPerformed
        Consultar_saldo cs = new Consultar_saldo();
        this.setVisible(false);
        cs.setVisible(true);
    }//GEN-LAST:event_bt_saldoActionPerformed

    private void bt_despositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_despositarActionPerformed
        Deposito d = new Deposito();
        this.setVisible(false);
        d.setVisible(true);
    }//GEN-LAST:event_bt_despositarActionPerformed

    private void bt_sacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sacarActionPerformed
        Saque s = new Saque();
        this.setVisible(false);
        s.setVisible(true);
    }//GEN-LAST:event_bt_sacarActionPerformed

    private void bt_comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_comprarActionPerformed
        CompraCriptomoedas cc = new CompraCriptomoedas();
        this.setVisible(false);
        cc.setVisible(true);
    }//GEN-LAST:event_bt_comprarActionPerformed

    private void bt_venderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_venderActionPerformed
        VendaCriptomoedas vc = new VendaCriptomoedas();
        this.setVisible(false);
        vc.setVisible(true);
    }//GEN-LAST:event_bt_venderActionPerformed

    private void bt_extratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_extratoActionPerformed
        Consultar_extrato ce = new Consultar_extrato();
        this.setVisible(false);
        ce.setVisible(true);
    }//GEN-LAST:event_bt_extratoActionPerformed

    private void bt_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_atualizarActionPerformed
        AtualizarCotacao ac = new AtualizarCotacao();
        this.setVisible(false);
        ac.setVisible(true);
    }//GEN-LAST:event_bt_atualizarActionPerformed

    private void bt_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bt_sairActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Menu_Investidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Menu_Investidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Menu_Investidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Menu_Investidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Menu_Investidor().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Sair;
    private javax.swing.JButton bt_atualizar;
    private javax.swing.JButton bt_comprar;
    private javax.swing.JButton bt_despositar;
    private javax.swing.JButton bt_extrato;
    private javax.swing.JButton bt_sacar;
    private javax.swing.JButton bt_sair;
    private javax.swing.JButton bt_saldo;
    private javax.swing.JButton bt_vender;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    // End of variables declaration//GEN-END:variables
}
